# Generated by Django 5.0.1 on 2024-02-21 08:32

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_preview",
            field=models.ImageField(
                blank=True,
                storage=core.utils.select_storage,
                upload_to=core.utils.get_storage_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=core.utils.select_storage,
                upload_to=core.utils.get_storage_path,
            ),
        ),
    ]
