# Generated by Django 5.0.1 on 2024-01-27 16:19

import core.utils
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, upload_to=core.utils.get_storage_path),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Phone number"
            ),
        ),
    ]
